export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const FETCH_RANDOM_PROJECT = "FETCH_RANDOM_PROJECT";
export const FETCH_RANDOM_PROJECT_START = "FETCH_RANDOM_PROJECT_START";
export const FETCH_RANDOM_PROJECT_SUCCESS = "FETCH_RANDOM_PROJECT_SUCCESS";