export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECT_BY_ID = "FETCH_PROJECT_BY_ID";
export const FETCH_PROJECT_DETAILS = "FETCH_PROJECT_DETAILS";
export const FETCH_PROJECT_DETAILS_SUCCESS = "FETCH_PROJECT_DETAILS_SUCCESS";
export const FETCH_PROJECT_DETAILS_LOADING = "FETCH_PROJECT_DETAILS_LOADING";
export const FETCH_PROJECTS_LOADING = "FETCH_PROJECTS_LOADING";
export const FETCH_MAIN_PAGE_PROJECTS = "FETCH_MAIN_PAGE_PROJECTS";
export const FETCH_MAIN_PAGE_PROJECTS_SUCCESS = "FETCH_MAIN_PAGE_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const FETCH_RANDOM_PROJECT = "FETCH_RANDOM_PROJECT";
export const FETCH_RANDOM_PROJECT_START = "FETCH_RANDOM_PROJECT_START";
export const FETCH_RANDOM_PROJECT_SUCCESS = "FETCH_RANDOM_PROJECT_SUCCESS";

export const SAVE_PROJECT_DETAILS = "SAVE_PROJECT_DETAILS";