export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECT_DETAILS = "FETCH_PROJECT_DETAILS";
export const FETCH_PROJECT_DETAILS_SUCCESS = "FETCH_PROJECT_DETAILS_SUCCESS";
export const FETCH_PROJECTS_LOADING = "FETCH_PROJECTS_LOADING";
export const FETCH_MAIN_PAGE_PROJECTS = "FETCH_MAIN_PAGE_PROJECTS";
export const FETCH_MAIN_PAGE_PROJECTS_SUCCESS = "FETCH_MAIN_PAGE_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const SAVE_PROJECT_DETAILS = "SAVE_PROJECT_DETAILS";
export const SAVE_PROJECT_DETAILS_SUCCESS = "SAVE_PROJECT_DETAILS_SUCCESS";

export const PROJECT_DETAILS_LOADING = "PeROJECT_DETAILS_LOADING";

export const AUTHORIZE_USER = "AUTHORIZE_USER";
export const AUTHORIZE_USER_SUCCESS = "AUTHORIZE_USER_SUCCESS";
export const AUTHORIZE_USER_FAIL = "AUTHORIZE_USER_FAIL";
export const UNAUTHORIZE_USER = "UNAUTHORIZE_USER";
export const UNAUTHORIZE_USER_SUCCESS = "UNAUTHORIZE_USER_SUCCESS";
export const UNAUTHORIZE_USER_FAIL = "UNAUTHORIZE_USER_FAIL";
